### ISSUE TITLE
Remote server sendfile missing / when using environment var WEBP_IMAGE_PATH

### ISSUE THREAD

**Issue by BabyDino** [webp-sh/webp_server_go#383]
**Describe the bug**
Same issue as #381, but only if you set the `WEBP_IMG_PATH` instead of using the config file, there is a missing `/` after `https://`. Using the config file now works thanks to #382.

**To Reproduce**
Refer to #381, but now set `WEBP_IMG_PATH=https://s3.dualstack.eu-west-1.amazonaws.com` without using a config file.

**Expected behavior**
Send the correct output ;)

**Environment (please complete the following information):**
 - OS: Linux/Docker
 - latest

**Comment by n0vad3v** [comment]
Hi @BabyDino ,could you please share full environment variables and `config.json`, as well as your running WebP Server Go version?

**Comment by BabyDino** [comment]
Hi, sorry for the delay. This is our docker compose:

```
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    environment:
      - MALLOC_ARENA_MAX=1
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.6
      - WEBP_QUALITY=80
      - WEBP_IMG_PATH=https://s3.dualstack.eu-west-1.amazonaws.com
      - WEBP_ENABLE_EXTRA_PARAMS=true
      - WEBP_ALLOWED_TYPES=*
      - WEBP_EXTRA_PARAMS_CROP_INTERESTING=InterestingCentre
      - WEBP_MAX_CACHE_SIZE=10240
    volumes:
      - /path/to/pics:/opt/pics
      - ./exhaust:/opt/exhaust
      - ./metadata:/opt/metadata
    ports:
      -  127.0.0.1:3333:3333
```

Visiting localhost:3333 will output:

```
sendfile: file https:/s3.dualstack.eu-west-1.amazonaws.com not found
```

**Comment by BabyDino** [comment]
Hi @n0vad3v, this issue is still present in v0.13.4 with the config above.

**Comment by n0vad3v** [comment]
@BabyDino Thanks for feedback, will check on that. 👀

**Comment by n0vad3v** [comment]
@BabyDino Cannot reproduce this problem using latest image:
```
time="2025-04-06T06:51:45Z" level=warning msg="Enable proxy based on ImgPath will be deprecated in future versions. Use IMG_MAP config options instead"

 
		▌ ▌   ▌  ▛▀▖ ▞▀▖                ▞▀▖
		▌▖▌▞▀▖▛▀▖▙▄▘ ▚▄ ▞▀▖▙▀▖▌ ▌▞▀▖▙▀▖ ▌▄▖▞▀▖
		▙▚▌▛▀ ▌ ▌▌   ▖ ▌▛▀ ▌  ▐▐ ▛▀ ▌   ▌ ▌▌ ▌
		▘ ▘▝▀▘▀▀ ▘   ▝▀ ▝▀▘▘   ▘ ▝▀▘▘   ▝▀ ▝▀
		
		WebP Server Go - v0.13.4
		Developed by WebP Server team. https://github.com/webp-sh

Allowed file types as source: [*]
Convert to WebP Enabled: true
Convert to AVIF Enabled: true
Convert to JXL Enabled: true
WebP Server Go is Running on http://0.0.0.0:3333
time="2025-04-06 06:51:45" level=info msg="MaxCacheSize is not 0, starting cache cleaning service" func="[92:webp_server_go/schedule.CleanCache]"
time="2025-04-06 06:51:51" level=info msg="Remote Addr is https://s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg, pinging for info..." func="[98:webp_server_go/handler.fetchRemoteImg]"
time="2025-04-06 06:51:52" level=info msg="Remote didn't return etag in header when getRemoteImageInfo, please check." func="[144:webp_server_go/handler.pingURL]"
time="2025-04-06 06:51:52" level=info msg="Remote file not found in remote-raw, re-fetching..." func="[119:webp_server_go/handler.fetchRemoteImg]"

```

Please make sure you're using the latest image, use `docker pull webpsh/webp-server-go` to get the latest one.

The encoding issue should be solved by https://github.com/webp-sh/webp_server_go/pull/395

**Comment by BabyDino** [comment]
I am, this is my full config:

```
services:
  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    environment:
      - MALLOC_ARENA_MAX=1
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.6
      - WEBP_QUALITY=80
      - WEBP_IMG_PATH=https://s3.dualstack.eu-west-1.amazonaws.com
      - WEBP_ENABLE_EXTRA_PARAMS=true
      - WEBP_ALLOWED_TYPES=*
      - WEBP_EXTRA_PARAMS_CROP_INTERESTING=InterestingCentre
      - WEBP_MAX_CACHE_SIZE=10240
    ports:
      -  3333:3333
```

Resulting in:

```
2025-04-06 11:02:21 
2025-04-06 11:02:21  
2025-04-06 11:02:21             ▌ ▌   ▌  ▛▀▖ ▞▀▖                ▞▀▖
2025-04-06 11:02:21             ▌▖▌▞▀▖▛▀▖▙▄▘ ▚▄ ▞▀▖▙▀▖▌ ▌▞▀▖▙▀▖ ▌▄▖▞▀▖
2025-04-06 11:02:21             ▙▚▌▛▀ ▌ ▌▌   ▖ ▌▛▀ ▌  ▐▐ ▛▀ ▌   ▌ ▌▌ ▌
2025-04-06 11:02:21             ▘ ▘▝▀▘▀▀ ▘   ▝▀ ▝▀▘▘   ▘ ▝▀▘▘   ▝▀ ▝▀
2025-04-06 11:02:21 
2025-04-06 11:02:21             WebP Server Go - v0.13.4
2025-04-06 11:02:21             Developed by WebP Server team. https://github.com/webp-sh
2025-04-06 11:02:21 
2025-04-06 11:02:21 Allowed file types as source: [*]
2025-04-06 11:02:21 Convert to WebP Enabled: true
2025-04-06 11:02:21 Convert to AVIF Enabled: false
2025-04-06 11:02:21 Convert to JXL Enabled: false
2025-04-06 11:02:21 WebP Server Go is Running on http://0.0.0.0:3333
2025-04-06 11:02:21 time="2025-04-06 09:02:21" level=info msg="MaxCacheSize is not 0, starting cache cleaning service" func="[92:webp_server_go/schedule.CleanCache]"
2025-04-06 11:02:33 time="2025-04-06 09:02:33" level=warning msg="Could not load https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: open https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: no such file or directory" func="[90:webp_server_go/helper.getImageMeta]"
2025-04-06 11:02:33 time="2025-04-06 09:02:33" level=info msg="Resize https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg itself to exhaust/local/ab7b9dec276f4f69" func="[107:webp_server_go/encoder.ResizeItself]"
2025-04-06 11:02:33 time="2025-04-06 09:02:33" level=warning msg="Could not load https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: open https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: no such file or directory" func="[120:webp_server_go/encoder.ResizeItself]"
2025-04-06 11:02:33  - [2025-04-06 09:02:33] GET /v1/image.jpg 404  PostmanRuntime/7.43.3
```

I have the same thing, both in our cluster and on my WSL host.

**Comment by mgl-pub** [comment]
If you add the parameter, you cannot download the remote image. If you do not add the parameter, it will display normally.
like this： /assets/2024/06/14/2Kvr975cVn5T8058C.png -------------- it ok 
/assets/2024/06/14/2Kvr975cVn5T8058C.png?width=200 --------- get error  other params same error  



time="2025-04-07 12:38:33" level=info msg="Remote Addr is http://minio:9000/assets/2024/06/14/2Kvr975cVn5T8058C.png%3Fwidth=100, pinging for info..." func="[98:webp_server_go/handler.fetchRemoteImg]"
time="2025-04-07 12:38:33" level=info msg="Remote didn't return etag in header when getRemoteImageInfo, please check." func="[144:webp_server_go/handler.pingURL]"
time="2025-04-07 12:38:33" level=info msg="Remote file not found in remote-raw, re-fetching..." func="[119:webp_server_go/handler.fetchRemoteImg]"
time="2025-04-07 12:38:33" level=error msg="remote returned 404 Not Found when fetching remote image" func="[44:webp_server_go/handler.downloadFile]"
time="2025-04-07 12:38:33" level=warning msg="Could not load pics/assets/2024/06/14/2Kvr975cVn5T8058C.png?width=100: open pics/assets/2024/06/14/2Kvr975cVn5T8058C.png?width=100: no such file or directory" func="[90:webp_server_go/helper.getImageMeta]"

**Comment by n0vad3v** [comment]
@BabyDino 0.13.5 is released, and should fix these two problems stated above, please give it a try to see if it works.

**Comment by BabyDino** [comment]
@n0vad3v Still the same issue on 0.13.5 with the config above.

```
2025-04-23 11:03:52 
2025-04-23 11:03:52  
2025-04-23 11:03:52             ▌ ▌   ▌  ▛▀▖ ▞▀▖                ▞▀▖
2025-04-23 11:03:52             ▌▖▌▞▀▖▛▀▖▙▄▘ ▚▄ ▞▀▖▙▀▖▌ ▌▞▀▖▙▀▖ ▌▄▖▞▀▖
2025-04-23 11:03:52             ▙▚▌▛▀ ▌ ▌▌   ▖ ▌▛▀ ▌  ▐▐ ▛▀ ▌   ▌ ▌▌ ▌
2025-04-23 11:03:52             ▘ ▘▝▀▘▀▀ ▘   ▝▀ ▝▀▘▘   ▘ ▝▀▘▘   ▝▀ ▝▀
2025-04-23 11:03:52 
2025-04-23 11:03:52             WebP Server Go - v0.13.5
2025-04-23 11:03:52             Developed by WebP Server team. https://github.com/webp-sh
2025-04-23 11:03:52 
2025-04-23 11:03:52 Allowed file types as source: [*]
2025-04-23 11:03:52 Convert to WebP Enabled: true
2025-04-23 11:03:52 Convert to AVIF Enabled: false
2025-04-23 11:03:52 Convert to JXL Enabled: false
2025-04-23 11:03:52 WebP Server Go is Running on http://0.0.0.0:3333
2025-04-23 11:03:52 time="2025-04-23 09:03:52" level=info msg="MaxCacheSize is not 0, starting cache cleaning service" func="[92:webp_server_go/schedule.CleanCache]"
2025-04-23 11:04:10 time="2025-04-23 09:04:10" level=warning msg="Could not load https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: open https:/s3.dualstack.eu-west-1.amazonaws.com/v1/image.jpg: no such file or directory" func="[92:webp_server_go/helper.getImageMeta]"
```

**Comment by n0vad3v** [comment]
Thanks for feedback @BabyDino , I've located the problem and should be fixed by https://github.com/webp-sh/webp_server_go/pull/399/commits/4821118100ae9e371d1624b24ffce200e78fd560 in https://github.com/webp-sh/webp_server_go/pull/399

**Comment by n0vad3v** [comment]
@BabyDino  0.13.6 is released, please check if this version has fixed the issue.

**Comment by BabyDino** [comment]
Yes I just pulled the image, looks good on inital tests!
